component: website
name: websitedemo
org: test
app: websiteApp
stage: dev

inputs:
  src:
    src: ./
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: my-bucket
  protocol: http
